import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://rec.group"),
  title: "Sito Web PMI da €700 | Risparmia 75% vs Agenzie — SEO, AEO & AI 2026 | rec.group Catania",
  description: "Sito web professionale da €700 (mercato 2026: €2.000–8.000). Gestionale su misura da €900 una tantum — concorrenza: €5.000–8.000. ROI medio SEO per PMI: 748%. Core Web Vitals, AI, GEO e accessibilità WCAG/EAA inclusi. Incentivi Transizione 5.0 fino al 45% + Voucher MISE 50%. Consegna in 14 giorni. Preventivo gratuito in 24h — freelancer e PMI italiane.",
  keywords: [
    "agenzia digitale Catania",
    "sito web professionale freelancer",
    "gestionale personalizzato PMI",
    "software gestionale su misura piccola impresa",
    "realizzazione sito web PMI Italia",
    "sito web personal trainer prezzo",
    "digitalizzazione piccola impresa",
    "automazione gestione clienti",
    "menu digitale ristorante QR code",
    "agenzia web Sicilia preventivo gratuito",
    "soluzioni digitali freelancer Italia",
    "trasformazione digitale PMI",
    "gestionale prenotazioni online",
    "sito web vetrina professionale Catania",
    "rec group Catania",
    "sito web da 700 euro PMI",
    "gestionale web senza canone mensile",
    "automazione AI freelancer Italia",
    "chatbot AI piccola impresa",
    "preventivo sito web gratuito 2026",
    "agenzia digitale Sicilia prezzi",
    "crescita online PMI 2026",
    "web agency economica Italia",
    "integrazioni app azienda automazione",
    "identità digitale professionista italiano",
    "quanto costa un sito web 2026",
    "quanto costa realizzare un sito web PMI",
    "realizzare sito web prezzi 2026 Italia",
    "sito web a basso costo qualità professionale",
    "web agency senza canone mensile",
    "costo gestionale personalizzato PMI",
    "agenzia web preventivo online gratuito",
    "sito web professionale economico Italia",
    "metà prezzo sito web professionale",
    "costo software gestionale su misura 2026",
    "quanto costa un gestionale personalizzato PMI 2026",
    "prezzo sito web vetrina PMI 2026 Italia",
    "gestionale economico alternativa TeamSystem SAP",
    "sito web aziendale prezzo PMI 2026",
    "agenzia web o freelance conviene 2026",
    "GEO generative engine optimization PMI Italia",
    "agenti AI autonomi piccola impresa 2026",
    "alternativa odoo economico Italia PMI",
    "alternativa teamsystem gestionale economico",
    "risparmia 75 percento sito web professionale",
    "sito web 700 euro catania sicilia",
    "gestionale personalizzato 900 euro su misura",
    "web agency prezzi chiari senza sorprese",
    "digitalizzazione PMI Transizione 5.0 2026 incentivi",
    "core web vitals ottimizzazione sito PMI",
    "sito web professionale veloce mobile-first PMI",
    "gestionale web cloud senza installazione PMI",
    "automazione flussi lavoro n8n make zapier freelancer",
    "come avviare progetto digitale PMI guida",
    "green coding sito web sostenibile",
    "GenAI intelligenza artificiale generativa PMI",
    "marketing automation freelancer Italia 2026",
    "chatbot WhatsApp Business automazione",
    "landing page alta conversione professionista",
    "sito web accessibile WCAG normativa 2026",
    "indicizzazione AI motori ricerca generativi",
    "progressive web app PWA piccola impresa",
    "ROI SEO PMI italiane 748 percento",
    "gestionale su misura vs SaaS TeamSystem Fatture in Cloud",
    "sito web professionale consegna 2 settimane PMI",
    "agenzia digitale specializzata PMI micro impresa",
    "ottimizzazione GEO Google AI Overview PMI 2026",
    "costo digitalizzazione azienda PMI 2026 guida",
    "consulenza digitale gratuita PMI freelancer Italia",
    "sito web aziendale senza canone manutenzione",
    "ERP economico piccola impresa alternativa cloud",
    "NIS2 cybersecurity sicurezza informatica PMI 2026",
    "European Accessibility Act accessibilità digitale PMI",
    "credito imposta beni digitali 4.0 PMI 2026",
    "alternativa Fatture in Cloud gestionale personalizzato PMI",
    "voucher digitalizzazione Mezzogiorno 70 percento PMI",
    "sviluppo software su misura piccola impresa economico",
    "sito web PMI non ottimizzato 72 percento Italia",
    "confronto tariffe web agency freelancer Italia 2026",
    "gestionale personalizzato economico 900 euro vs SaaS 50 mese",
    "accessibilità WCAG EAA sito web obbligatorio 2026",
    "AEO answer engine optimization PMI Italia 2026",
    "answer engine optimization come funziona PMI",
    "marketing locale AI PMI Italia 2026",
    "intelligenza artificiale marketing locale piccola impresa",
    "conversion rate optimization PMI sito web",
    "CRO ottimizzazione conversioni sito web freelancer",
    "bandi regione Sicilia digitalizzazione PMI 2026",
    "contributi provinciali sito web piccola impresa 60 percento",
    "sito web vetrina piccola impresa 800 3000 euro prezzi reali",
    "agenzie web specializzate PMI Italia 2026 verticali",
    "web agency verticale settore PMI Italia",
    "perché il mio sito web non compare su Google PMI",
    "sito web non ottimizzato perdita clienti PMI",
    "agenzia web trasparenza prezzi senza sorprese Italia",
  ],
  authors: [{ name: "rec.group" }],
  creator: "rec.group",
  openGraph: {
    title: "Sito Web PMI da €700, Gestionale da €900 — ROI 748% Medio | rec.group 2026",
    description: "Il 72% delle PMI ha un sito — ma solo il 45% è ottimizzato. Noi: siti da €700 e gestionali da €900 (concorrenza: €5.000–8.000). SEO ROI 748%, accessibilità EAA, Core Web Vitals e AI inclusi. Incentivi fino al 70% nel Mezzogiorno. Preventivo gratuito 24h — risponde un umano.",
    type: "website",
    locale: "it_IT",
    siteName: "rec.group",
    url: "https://rec.group",
  },
  twitter: {
    card: "summary_large_image",
    title: "Sito Web PMI da €700 — Gestionale €900 Zero Canoni | rec.group 2026",
    description: "Solo il 45% dei siti PMI italiani è ottimizzato e mobile-first. Il tuo? Sito da €700, gestionale da €900 zero canoni. ROI SEO 748%. Accessibilità EAA e NIS2-ready inclusi. Incentivi 5.0 + Voucher MISE 50%.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
    },
  },
  alternates: {
    canonical: "https://rec.group",
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": "https://rec.group/#website",
      url: "https://rec.group",
      name: "rec.group — Agenzia Digitale per Freelancer e PMI",
      description:
        "Siti web professionali, gestionali su misura e automazioni digitali per freelancer e PMI italiane. Preventivo gratuito in 24h.",
      inLanguage: "it-IT",
      publisher: { "@id": "https://rec.group/#organization" },
      potentialAction: [
        {
          "@type": "ContactAction",
          target: "https://rec.group/#contatti",
          name: "Richiedi Preventivo Gratuito in 24h",
        },
        {
          "@type": "SearchAction",
          target: {
            "@type": "EntryPoint",
            urlTemplate: "https://rec.group/?q={search_term_string}",
          },
          "query-input": "required name=search_term_string",
        },
      ],
    },
    {
      "@type": "Organization",
      "@id": "https://rec.group/#organization",
      name: "rec.group",
      url: "https://rec.group",
      logo: {
        "@type": "ImageObject",
        url: "https://rec.group/logo.png",
        width: 200,
        height: 60,
      },
      email: "recgroup.business@gmail.com",
      description:
        "Agenzia digitale a Catania specializzata in siti web professionali, gestionali personalizzati, social media marketing e automazione per freelancer, PMI, ristoranti e professionisti italiani.",
      foundingLocation: {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          addressLocality: "Catania",
          addressRegion: "Sicilia",
          addressCountry: "IT",
        },
      },
      areaServed: [
        { "@type": "City", name: "Catania" },
        { "@type": "AdministrativeArea", name: "Sicilia" },
        { "@type": "Country", name: "Italia" },
      ],
      slogan: "Soluzioni digitali su misura — zero canoni mensili",
      foundingDate: "2024",
      knowsLanguage: ["it"],
      contactPoint: [
        {
          "@type": "ContactPoint",
          contactType: "customer service",
          email: "recgroup.business@gmail.com",
          availableLanguage: "Italian",
          areaServed: "IT",
        },
        {
          "@type": "ContactPoint",
          contactType: "sales",
          email: "recgroup.business@gmail.com",
          availableLanguage: "Italian",
          areaServed: "IT",
        },
      ],
      sameAs: [],
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.9",
        reviewCount: "10",
        bestRating: "5",
        worstRating: "1",
      },
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "Servizi Digitali rec.group",
        itemListElement: [
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-sito-web",
              name: "Realizzazione Siti Web Professionali per PMI",
              description:
                "Siti web su misura per freelancer, PMI e professionisti. Design moderno, ottimizzazione SEO e velocità garantita. Online in 1–2 settimane.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
            priceSpecification: {
              "@type": "PriceSpecification",
              price: "700",
              priceCurrency: "EUR",
              description: "Sito vetrina professionale con SEO incluso",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-gestionale",
              name: "Software Gestionale Personalizzato per Piccola Impresa",
              description:
                "Gestionali web-based su misura per piccole e medie imprese: prenotazioni, magazzino, clienti, fatturazione. ROI medio in 6–12 mesi.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
            priceSpecification: {
              "@type": "PriceSpecification",
              price: "900",
              priceCurrency: "EUR",
              description: "Gestionale personalizzato una tantum",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-social",
              name: "Social Media Management per PMI",
              description:
                "Gestione social media professionale con strategia di contenuti, post creativi e crescita organica per la tua azienda italiana.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-automazione",
              name: "Automazione Digitale e CRM per Freelancer",
              description:
                "Automazioni per risparmiare 8–15 ore a settimana: CRM, email marketing, flussi di lavoro automatizzati e integrazioni tra app.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-ecommerce",
              name: "E-commerce Professionale per PMI",
              description:
                "Shop online ottimizzato SEO con catalogo prodotti, pagamenti, gestione ordini e Google Shopping. Mercato e-commerce italiano: 71 miliardi nel 2026.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
            priceSpecification: {
              "@type": "PriceSpecification",
              price: "1500",
              priceCurrency: "EUR",
              description: "E-commerce completo con SEO e-commerce incluso",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-menu",
              name: "Menu Digitale QR Code per Ristoranti",
              description:
                "Menu QR code interattivo e aggiornabile in tempo reale per ristoranti, bar e locali in Sicilia e Italia.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: [
                { "@type": "AdministrativeArea", name: "Sicilia" },
                { "@type": "Country", name: "Italia" },
              ],
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-identita",
              name: "Brand Identity Digitale per Professionisti e PMI",
              description:
                "Identità digitale completa: logo, palette colori, tipografia e presenza coordinata su web e social per freelancer e PMI italiane.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
          },
        ],
      },
    },
    {
      "@type": ["LocalBusiness", "ProfessionalService"],
      "@id": "https://rec.group/#localbusiness",
      name: "rec.group — Agenzia Digitale Catania",
      image: "https://rec.group/logo.png",
      url: "https://rec.group",
      email: "recgroup.business@gmail.com",
      telephone: "",
      address: {
        "@type": "PostalAddress",
        addressLocality: "Catania",
        addressRegion: "CT",
        postalCode: "95100",
        addressCountry: "IT",
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: 37.5079,
        longitude: 15.0830,
      },
      description: "Agenzia digitale a Catania: siti web professionali da €700, gestionali su misura da €900 senza canone mensile, automazioni AI e social media per freelancer e PMI in tutta Italia. Preventivo gratuito in 24h.",
      slogan: "Soluzioni digitali su misura — zero canoni mensili",
      priceRange: "€€",
      currenciesAccepted: "EUR",
      paymentAccepted: "Bonifico, Carta di Credito, PayPal",
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.9",
        reviewCount: "10",
        bestRating: "5",
        worstRating: "1",
      },
      openingHoursSpecification: [
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
          opens: "09:00",
          closes: "18:00",
        },
      ],
      knowsAbout: [
        "realizzazione siti web PMI",
        "gestionale personalizzato piccola impresa",
        "social media marketing Catania",
        "automazione digitale freelancer",
        "sito web personal trainer",
        "e-commerce PMI Italia",
        "menu digitale QR code ristorante",
        "identità digitale professionista",
        "agenzia web Sicilia",
        "transizione 5.0 digitalizzazione PMI",
        "intelligenza artificiale piccola impresa",
        "voucher digitalizzazione MISE",
        "automazione workflow n8n make zapier PMI",
        "CRM personalizzato freelancer Italia",
        "fatturazione elettronica integrata gestionale",
        "lead generation automatica piccola impresa",
        "next.js TypeScript sito web veloce PMI",
        "Google Business Profile ottimizzazione locale",
        "preventivi automatici CRM no-code",
        "agenti AI autonomi automazione PMI 2026",
        "software gestionale senza canone mensile",
        "sito web one-page professionale freelancer",
        "web app personalizzata piccola impresa",
        "consulenza digitale PMI Catania Sicilia",
        "green coding sito web sostenibile PMI",
        "GenAI intelligenza artificiale generativa PMI 2026",
        "marketing automation piccola impresa Italia",
        "sito web accessibile WCAG PMI",
        "progressive web app PWA freelancer",
        "chatbot WhatsApp Business automazione PMI",
        "landing page conversione freelancer professionista",
        "schema markup structured data SEO locale",
        "indicizzazione AI Perplexity ChatGPT azienda locale",
        "e-commerce PMI italiane 71 miliardi 2026",
        "brand identity digitale professionista freelancer",
        "ingegnere AI integrazione processi aziendali PMI",
        "voucher consulenza innovazione MIMIT 50 percento",
        "bandi digitalizzazione PMI 2026 finanziamenti",
        "SearchGPT Perplexity ottimizzazione visibilità AI",
        "costo social media manager PMI freelancer Italia",
        "menu digitale allergeni multilingua ristorante",
        "rich snippets Google structured data azienda locale",
        "AI Overviews Google citazione azienda locale 2026",
        "AEO answer engine optimization PMI Italia 2026",
        "marketing locale AI intelligenza artificiale PMI 2026",
        "conversion rate optimization sito web PMI freelancer",
        "bandi regione Sicilia digitalizzazione contributi PMI",
      ],
      makesOffer: [
        { "@id": "https://rec.group/#service-sito-web" },
        { "@id": "https://rec.group/#service-gestionale" },
        { "@id": "https://rec.group/#service-social" },
        { "@id": "https://rec.group/#service-automazione" },
        { "@id": "https://rec.group/#service-ecommerce" },
        { "@id": "https://rec.group/#service-menu" },
        { "@id": "https://rec.group/#service-identita" },
      ],
      hasMap: "https://maps.google.com/?cid=rec.group+catania",
      additionalType: "https://schema.org/InternetMarketingService",
      parentOrganization: { "@id": "https://rec.group/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": "https://rec.group/#faq",
      mainEntity: [
        {
          "@type": "Question",
          name: "Quanto costa un sito web professionale per freelancer o PMI?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Un sito vetrina professionale parte da €700 — design, sviluppo e ottimizzazione SEO inclusi. Per un freelancer che vuole acquisire clienti online è l'investimento con il ROI più rapido: più visibilità, più credibilità, meno tempo perso in preventivi a freddo. Il preventivo è gratuito, dettagliato e senza sorprese.",
          },
        },
        {
          "@type": "Question",
          name: "Conviene un gestionale personalizzato rispetto ai software standard?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "I software generici come TeamSystem o SAP costano 50–150€/mese per utente — e paghi funzioni che non usi mai. Il nostro gestionale su misura parte da €900 una tantum, costruito esatto per il tuo flusso di lavoro. In media le PMI italiane recuperano l'investimento in 6–12 mesi grazie al tempo risparmiato.",
          },
        },
        {
          "@type": "Question",
          name: "Quanto tempo si risparmia davvero con l'automazione dei processi?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Le PMI italiane risparmiano mediamente 8–15 ore a settimana per dipendente dopo aver automatizzato fatturazione, solleciti pagamenti, gestione appuntamenti e report. Per un freelancer o un piccolo studio, significa recuperare 2–4 giorni interi al mese — tempo che puoi rivendere ai clienti.",
          },
        },
        {
          "@type": "Question",
          name: "Le PMI possono accedere agli incentivi fiscali Transizione 5.0?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Sì. Il piano Transizione 5.0 del MIMIT copre fino al 45% degli investimenti in beni digitali per le PMI italiane — siti web, gestionali e automazioni compresi. Un progetto da €2.000 può costarne effettivamente €1.100. Ti aiutiamo a capire cosa spetta alla tua impresa prima ancora di iniziare.",
          },
        },
        {
          "@type": "Question",
          name: "Quanto tempo ci vuole per avere un sito web operativo?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Un sito vetrina è online in 1–2 settimane. Un e-commerce o una piattaforma con area riservata richiede 3–6 settimane. Prima di iniziare ti diamo una data di consegna precisa — e la rispettiamo.",
          },
        },
        {
          "@type": "Question",
          name: "Il sito web include l'ottimizzazione SEO per Google?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Sì, sempre. Ogni sito parte già ottimizzato: struttura semantica, meta tag, Core Web Vitals, mobile-first e velocità di caricamento. Non è un extra a pagamento — è il minimo per comparire su Google e portare traffico organico nel tempo.",
          },
        },
        {
          "@type": "Question",
          name: "Conviene aprire un e-commerce nel 2026? Quali sono i costi reali?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Il mercato e-commerce italiano ha superato i 71 miliardi di euro nel 2026: la domanda c'è. Un e-commerce professionale con RecGroup parte da €1.500 — catalogo prodotti, pagamenti online, gestione ordini e SEO inclusi. Rientri dell'investimento tipici: 6–18 mesi per chi parte da zero.",
          },
        },
        {
          "@type": "Question",
          name: "Le PMI possono integrare l'intelligenza artificiale nella piccola impresa?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Sì, e nel 2026 è più accessibile di quanto pensi. Integriamo chatbot AI sul tuo sito (gestisce l'80% delle domande ricorrenti senza personale), automazioni basate su AI per generare preventivi e documenti in secondi, e dashboard intelligenti che analizzano i tuoi dati di vendita.",
          },
        },
        {
          "@type": "Question",
          name: "Esistono incentivi oltre a Transizione 5.0 per digitalizzare la mia impresa?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Sì. Oltre a Transizione 5.0 (fino al 45%), nel 2026 sono attivi il Voucher Digitalizzazione MISE — contributo a fondo perduto del 50% fino a €10.000 per PMI che investono in siti web, software e formazione digitale — e bandi regionali che variano da regione a regione.",
          },
        },
        {
          "@type": "Question",
          name: "È meglio affidarsi a un'agenzia web o a un freelancer per il mio sito?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Un freelancer lavora da solo: una sola competenza, nessun backup se è indisponibile. Un'agenzia come RecGroup unisce sviluppo, design, SEO e copy su ogni progetto — referente unico, tempi certi. E da noi un sito vetrina parte da €700: spesso meno di quanto chiede un freelancer senior.",
          },
        },
        {
          "@type": "Question",
          name: "Come ottenere più recensioni su Google Maps per far crescere la mia attività locale?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "L'81% dei consumatori italiani legge le recensioni Google prima di contattare un'attività locale — e Google Maps usa le recensioni come segnale di ranking diretto: più recensioni recenti e dettagliate hai, più alta è la probabilità di comparire nel 'local pack'. Cosa funziona nel 2026: chiedi la recensione subito dopo la consegna; invia un link diretto al profilo Google Business Profile via WhatsApp o email; invita il cliente a descrivere il problema risolto, non solo a dare stelle. Con le nostre automazioni WhatsApp Business, la richiesta viene inviata automaticamente 24 ore dopo ogni lavoro completato. Risultato tipico: +15–30 recensioni nei primi 90 giorni, con impatto misurabile sul posizionamento locale.",
          },
        },
        {
          "@type": "Question",
          name: "Google Ads o SEO: cosa conviene di più per una PMI italiana con budget limitato?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Google Ads porta lead in 24 ore ma smette non appena smetti di pagare — costo medio per click in Italia: €0,50–3,00, budget minimo efficace: €300–500/mese per una PMI locale. SEO porta traffico organico gratuito ma richiede 3–6 mesi per i primi risultati con un ROI a lungo termine superiore al 700%. Per una PMI con budget limitato: sito ottimizzato SEO come base permanente (incluso in ogni nostro progetto), Google Ads solo su campagne ad alto margine. Se hai bisogno di contatti entro 30 giorni parti con gli Ads; se vuoi costruire traffico qualificato nel tempo senza pagare per ogni click, investi nel SEO prima.",
          },
        },
        {
          "@type": "Question",
          name: "Lavorate solo a Catania o in tutta Italia?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Siamo di Catania, ma lavoriamo con freelancer e PMI in tutta Italia — da Milano a Palermo. Tutto avviene online: chiamate, consegne, supporto. La distanza non cambia la qualità del risultato.",
          },
        },
        {
          "@type": "Question",
          name: "Come si inizia a lavorare con RecGroup?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Con una chiamata gratuita di 30 minuti. Raccontaci il tuo progetto, le difficoltà attuali e gli obiettivi. Riceverai una proposta su misura entro 48 ore — senza impegno e senza costi anticipati.",
          },
        },
      ],
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-sito-web",
      name: "Realizzazione Siti Web Professionali per PMI e Freelancer",
      description:
        "Siti web su misura per freelancer, PMI e professionisti italiani. Design moderno mobile-first, ottimizzazione SEO, Core Web Vitals e velocità garantita. Online in 1–2 settimane da €700 tutto incluso.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Sviluppo Web",
      offers: {
        "@type": "Offer",
        price: "700",
        priceCurrency: "EUR",
        priceValidUntil: "2026-12-31",
        availability: "https://schema.org/InStock",
        description: "Sito vetrina professionale con SEO incluso",
      },
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-gestionale",
      name: "Software Gestionale Personalizzato per Piccola Impresa",
      description:
        "Gestionali web-based costruiti sul tuo flusso di lavoro: prenotazioni online, magazzino, clienti, fatturazione e report. Nessun canone mensile — pagamento una tantum da €900. ROI medio in 6–12 mesi.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Sviluppo Software",
      offers: {
        "@type": "Offer",
        price: "900",
        priceCurrency: "EUR",
        priceValidUntil: "2026-12-31",
        availability: "https://schema.org/InStock",
        description: "Gestionale personalizzato una tantum senza canone mensile",
      },
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-automazione",
      name: "Automazione Digitale e CRM per Freelancer e PMI Italiane",
      description:
        "Automazioni AI che risparmiano 8–15 ore a settimana: CRM, email marketing automatizzato, flussi di lavoro, integrazioni tra app e chatbot AI. Per freelancer e PMI italiane che vogliono crescere senza assumere.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Automazione Digitale",
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-social",
      name: "Social Media Marketing Professionale per PMI e Freelancer",
      description:
        "Gestione social media completa per freelancer e PMI italiane: strategia mensile, piano editoriale, contenuti professionali, campagne sponsorizzate e report con KPI reali. Post che generano richieste di preventivo — non solo like. Crescita organica e advertising su Instagram, Facebook, LinkedIn e TikTok.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Social Media Marketing",
      category: "Marketing Digitale",
      audience: {
        "@type": "Audience",
        audienceType: "Freelancer, PMI e professionisti italiani",
      },
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-ecommerce",
      name: "Realizzazione E-commerce Professionale per PMI Italiane",
      description:
        "Shop online ottimizzato SEO per PMI italiane: catalogo prodotti, pagamenti sicuri, gestione ordini, spedizioni e integrazione Google Shopping. Mercato e-commerce italiano oltre 71 miliardi nel 2026. ROI tipico: rientro dell'investimento in 6–18 mesi. Da €1.500 tutto incluso.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Sviluppo E-commerce",
      category: "Commercio Elettronico",
      offers: {
        "@type": "Offer",
        price: "1500",
        priceCurrency: "EUR",
        priceValidUntil: "2026-12-31",
        availability: "https://schema.org/InStock",
        description: "E-commerce completo con SEO, pagamenti e gestione ordini inclusi",
      },
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-menu",
      name: "Menu Digitale QR Code per Ristoranti Bar e Locali",
      description:
        "Menu digitale interattivo con QR code per ristoranti, bar, pizzerie e locali in Italia: aggiornabile in tempo reale, zero costi di stampa, design coordinato al brand. I clienti scansionano dal tavolo — tu aggiorni prezzi e piatti in un click. Multilingua, allergeni e foto piatti inclusi.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: [
        { "@type": "AdministrativeArea", name: "Sicilia" },
        { "@type": "Country", name: "Italia" },
      ],
      serviceType: "Menu Digitale QR Code",
      category: "Ristorazione Digitale",
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-identita",
      name: "Brand Identity Digitale per Professionisti e PMI",
      description:
        "Identità digitale completa per freelancer, professionisti e PMI italiane: logo professionale, palette colori, tipografia, tono di voce e presenza coordinata su web e social media. Un brand riconoscibile che ti differenzia dalla concorrenza locale e aumenta la fiducia dei clienti.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Brand Identity",
      category: "Identità Visiva e Branding",
    },
    {
      "@type": "ItemList",
      "@id": "https://rec.group/#service-list",
      name: "Tutti i Servizi Digitali rec.group per Freelancer e PMI",
      description: "Lista completa dei servizi digitali offerti da rec.group: siti web, gestionali, e-commerce, automazioni, social media, menu digitali e brand identity per freelancer e PMI italiane.",
      numberOfItems: 7,
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Siti Web Professionali da €700",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-sito-web" },
        },
        {
          "@type": "ListItem",
          position: 2,
          name: "Gestionali Personalizzati da €900",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-gestionale" },
        },
        {
          "@type": "ListItem",
          position: 3,
          name: "E-commerce Professionale da €1.500",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-ecommerce" },
        },
        {
          "@type": "ListItem",
          position: 4,
          name: "Automazione Digitale e CRM",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-automazione" },
        },
        {
          "@type": "ListItem",
          position: 5,
          name: "Social Media Marketing PMI",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-social" },
        },
        {
          "@type": "ListItem",
          position: 6,
          name: "Menu Digitale QR Code Ristoranti",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-menu" },
        },
        {
          "@type": "ListItem",
          position: 7,
          name: "Brand Identity Digitale",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-identita" },
        },
      ],
    },
    {
      "@type": "SoftwareApplication",
      "@id": "https://rec.group/#software-gestionale",
      name: "Gestionale PMI su Misura — rec.group",
      applicationCategory: "BusinessApplication",
      applicationSubCategory: "Gestionale Web PMI",
      operatingSystem: "Web, iOS, Android",
      description:
        "Software gestionale web-based personalizzato per piccola impresa: prenotazioni online, CRM clienti, magazzino, fatturazione e report automatici. Pagamento una tantum da €900 — zero canoni mensili. ROI medio in 6–12 mesi per PMI italiane.",
      featureList: [
        "Gestione prenotazioni online",
        "CRM clienti personalizzato",
        "Fatturazione e preventivi automatici",
        "Report e dashboard dati",
        "Integrazione pagamenti online",
        "Accesso multi-dispositivo",
        "Backup automatico dati",
        "Supporto incluso nel prezzo",
      ],
      softwareVersion: "1.0",
      inLanguage: "it-IT",
      provider: { "@id": "https://rec.group/#organization" },
      audience: {
        "@type": "Audience",
        audienceType: "Freelancer e PMI italiane con 1–20 dipendenti",
        geographicArea: { "@type": "Country", name: "Italia" },
      },
      offers: {
        "@type": "Offer",
        price: "900",
        priceCurrency: "EUR",
        priceValidUntil: "2026-12-31",
        availability: "https://schema.org/InStock",
        description: "Gestionale personalizzato una tantum — nessun canone mensile",
        seller: { "@id": "https://rec.group/#organization" },
      },
    },
    {
      "@type": "WebPage",
      "@id": "https://rec.group/#webpage",
      url: "https://rec.group",
      name: "Sito Web da €700 per PMI e Freelancer | rec.group Catania",
      isPartOf: { "@id": "https://rec.group/#website" },
      about: { "@id": "https://rec.group/#organization" },
      primaryImageOfPage: {
        "@type": "ImageObject",
        url: "https://rec.group/og-image.png",
        width: 1200,
        height: 630,
      },
      datePublished: "2024-01-01",
      dateModified: "2026-07-04",
      description:
        "Siti web professionali da €700, gestionali su misura da €900 senza canone mensile e automazioni AI per freelancer e PMI italiane. Preventivo gratuito in 24h.",
      breadcrumb: { "@id": "https://rec.group/#breadcrumb" },
      inLanguage: "it-IT",
      speakable: {
        "@type": "SpeakableSpecification",
        cssSelector: ["h1", "h2", "[data-speakable]"],
      },
      potentialAction: {
        "@type": "ReadAction",
        target: ["https://rec.group"],
      },
    },
    {
      "@type": "HowTo",
      "@id": "https://rec.group/#howto-progetto",
      name: "Come avviare il tuo progetto digitale con RecGroup",
      description:
        "Guida passo-passo per freelancer e PMI italiane: dalla chiamata gratuita alla consegna del sito web o gestionale su misura. Tutto online, senza impegno.",
      totalTime: "P14D",
      estimatedCost: {
        "@type": "MonetaryAmount",
        currency: "EUR",
        value: "700",
      },
      step: [
        {
          "@type": "HowToStep",
          position: 1,
          name: "Richiedi un preventivo gratuito",
          text: "Compila il modulo di contatto o scrivi a recgroup.business@gmail.com. Rispondiamo entro 24 ore con una proposta su misura — senza impegno e senza costi anticipati.",
          url: "https://rec.group/#contatti",
        },
        {
          "@type": "HowToStep",
          position: 2,
          name: "Chiamata conoscitiva di 30 minuti",
          text: "Raccontaci il tuo progetto, le difficoltà attuali e gli obiettivi di business. Analizziamo insieme le esigenze specifiche della tua attività e identifichiamo la soluzione digitale più efficace.",
        },
        {
          "@type": "HowToStep",
          position: 3,
          name: "Ricevi la proposta dettagliata entro 48 ore",
          text: "Ti inviamo una proposta completa con tempi, costi e funzionalità — tutto trasparente, senza costi nascosti. Sito web da €700, gestionale da €900, automazioni su misura.",
        },
        {
          "@type": "HowToStep",
          position: 4,
          name: "Sviluppo e consegna del progetto",
          text: "Sito vetrina online in 1–2 settimane, e-commerce in 3–6 settimane. Ti diamo una data di consegna precisa e la rispettiamo. Supporto incluso nel prezzo dopo la consegna.",
        },
      ],
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-1",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Luca M." },
      reviewBody: "Sito professionale consegnato in 12 giorni, SEO già visibile su Google dopo 3 settimane. Prezzo onesto, zero sorprese in fattura.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-04-15",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-2",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Alessia T." },
      reviewBody: "Ho sostituito TeamSystem con il loro gestionale su misura da €900. Ho recuperato l'investimento in 7 mesi solo di abbonamenti risparmiati. Consigliatissimi.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-05-20",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-3",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Davide R." },
      reviewBody: "Automazioni WhatsApp Business e CRM integrato: risparmio 10 ore a settimana. Il chatbot AI gestisce il 70% delle domande dei clienti senza di me.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-06-08",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-4",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Marta S." },
      reviewBody: "Sito vetrina online in 11 giorni, già prima pagina Google per il mio settore. Il gestionale ha eliminato 3 fogli Excel. Investimento ammortizzato in 4 mesi.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-07-01",
      inLanguage: "it-IT",
    },
    {
      "@type": "BreadcrumbList",
      "@id": "https://rec.group/#breadcrumb",
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: "https://rec.group",
        },
        {
          "@type": "ListItem",
          position: 2,
          name: "Servizi Digitali",
          item: "https://rec.group/#servizi",
        },
        {
          "@type": "ListItem",
          position: 3,
          name: "Portfolio Progetti",
          item: "https://rec.group/#portfolio",
        },
        {
          "@type": "ListItem",
          position: 4,
          name: "Preventivo Gratuito",
          item: "https://rec.group/#contatti",
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it" className="h-full antialiased">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
