import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://rec.group"),
  title: "Sito Web PMI da €700 | Risparmia 75% vs Agenzie — SEO, AEO & AI 2026 | rec.group Catania",
  description: "L'88% delle PMI italiane è invisibile su ChatGPT e Gemini. Solo il 21% riceve ordini online, solo il 41% usa un gestionale strutturato (ISTAT 2026). Sito web da €700 (mercato: €2.000–8.000) e gestionale su misura da €900 zero canone. ROI SEO 748%. GEO, AEO, Core Web Vitals, EAA. Incentivi Transizione 5.0 fino al 45%. Preventivo gratuito in 24h.",
  keywords: [
    "agenzia digitale Catania",
    "sito web professionale freelancer",
    "gestionale personalizzato PMI",
    "software gestionale su misura piccola impresa",
    "realizzazione sito web PMI Italia",
    "sito web personal trainer prezzo",
    "digitalizzazione piccola impresa",
    "automazione gestione clienti",
    "menu digitale ristorante QR code",
    "agenzia web Sicilia preventivo gratuito",
    "soluzioni digitali freelancer Italia",
    "trasformazione digitale PMI",
    "gestionale prenotazioni online",
    "sito web vetrina professionale Catania",
    "rec group Catania",
    "sito web da 700 euro PMI",
    "gestionale web senza canone mensile",
    "automazione AI freelancer Italia",
    "chatbot AI piccola impresa",
    "preventivo sito web gratuito 2026",
    "agenzia digitale Sicilia prezzi",
    "crescita online PMI 2026",
    "web agency economica Italia",
    "integrazioni app azienda automazione",
    "identità digitale professionista italiano",
    "quanto costa un sito web 2026",
    "quanto costa realizzare un sito web PMI",
    "realizzare sito web prezzi 2026 Italia",
    "sito web a basso costo qualità professionale",
    "web agency senza canone mensile",
    "costo gestionale personalizzato PMI",
    "agenzia web preventivo online gratuito",
    "sito web professionale economico Italia",
    "metà prezzo sito web professionale",
    "costo software gestionale su misura 2026",
    "quanto costa un gestionale personalizzato PMI 2026",
    "prezzo sito web vetrina PMI 2026 Italia",
    "gestionale economico alternativa TeamSystem SAP",
    "sito web aziendale prezzo PMI 2026",
    "agenzia web o freelance conviene 2026",
    "GEO generative engine optimization PMI Italia",
    "agenti AI autonomi piccola impresa 2026",
    "alternativa odoo economico Italia PMI",
    "alternativa teamsystem gestionale economico",
    "risparmia 75 percento sito web professionale",
    "sito web 700 euro catania sicilia",
    "gestionale personalizzato 900 euro su misura",
    "web agency prezzi chiari senza sorprese",
    "digitalizzazione PMI Transizione 5.0 2026 incentivi",
    "core web vitals ottimizzazione sito PMI",
    "sito web professionale veloce mobile-first PMI",
    "gestionale web cloud senza installazione PMI",
    "automazione flussi lavoro n8n make zapier freelancer",
    "come avviare progetto digitale PMI guida",
    "green coding sito web sostenibile",
    "GenAI intelligenza artificiale generativa PMI",
    "marketing automation freelancer Italia 2026",
    "chatbot WhatsApp Business automazione",
    "landing page alta conversione professionista",
    "sito web accessibile WCAG normativa 2026",
    "indicizzazione AI motori ricerca generativi",
    "progressive web app PWA piccola impresa",
    "ROI SEO PMI italiane 748 percento",
    "gestionale su misura vs SaaS TeamSystem Fatture in Cloud",
    "sito web professionale consegna 2 settimane PMI",
    "agenzia digitale specializzata PMI micro impresa",
    "ottimizzazione GEO Google AI Overview PMI 2026",
    "costo digitalizzazione azienda PMI 2026 guida",
    "consulenza digitale gratuita PMI freelancer Italia",
    "sito web aziendale senza canone manutenzione",
    "ERP economico piccola impresa alternativa cloud",
    "NIS2 cybersecurity sicurezza informatica PMI 2026",
    "European Accessibility Act accessibilità digitale PMI",
    "credito imposta beni digitali 4.0 PMI 2026",
    "alternativa Fatture in Cloud gestionale personalizzato PMI",
    "voucher digitalizzazione Mezzogiorno 70 percento PMI",
    "sviluppo software su misura piccola impresa economico",
    "sito web PMI non ottimizzato 72 percento Italia",
    "confronto tariffe web agency freelancer Italia 2026",
    "gestionale personalizzato economico 900 euro vs SaaS 50 mese",
    "accessibilità WCAG EAA sito web obbligatorio 2026",
    "AEO answer engine optimization PMI Italia 2026",
    "answer engine optimization come funziona PMI",
    "marketing locale AI PMI Italia 2026",
    "intelligenza artificiale marketing locale piccola impresa",
    "conversion rate optimization PMI sito web",
    "CRO ottimizzazione conversioni sito web freelancer",
    "bandi regione Sicilia digitalizzazione PMI 2026",
    "contributi provinciali sito web piccola impresa 60 percento",
    "sito web vetrina piccola impresa 800 3000 euro prezzi reali",
    "agenzie web specializzate PMI Italia 2026 verticali",
    "web agency verticale settore PMI Italia",
    "sito web per avvocato studio legale prezzo 2026",
    "sito web per commercialista studio contabile professionale",
    "sito web per fisioterapista prenotazioni online 2026",
    "sito web per nutrizionista acquisire clienti online",
    "sito web per architetto portfolio professionale Italia",
    "sito web per psicologo terapeuta prenotazioni 2026",
    "sito web per geometra professionista preventivi online",
    "gestionale studio professionale freelancer 2026 su misura",
    "perché il mio sito web non compare su Google PMI",
    "sito web non ottimizzato perdita clienti PMI",
    "agenzia web trasparenza prezzi senza sorprese Italia",
    "programma gestionale su misura PMI Italia",
    "software gestionale micro impresa senza canone",
    "ERP personalizzabile piccola azienda economico",
    "alternativa SmartERP Zucchetti gestionale su misura",
    "prezzi trasparenti web agency PMI preventivo dettagliato",
    "sito web personal trainer prezzo 2026 Italia",
    "quanto costa sito personal trainer professionale",
    "sito web per personal trainer prenotazioni online",
    "personal trainer sito web gestionale clienti",
    "agenti AI autonomi piccola impresa 2026",
    "AI agent PMI italiane automazione intelligente",
    "agente AI preventivi automatici freelancer",
    "agenti intelligenti aziendali PMI costi 2026",
    "quanto costa implementare AI agent piccola impresa",
    "restyling sito web aziendale costi 2026 PMI",
    "quanto costa rifare sito web aziendale 2026",
    "60 percento PMI italiane usa ancora Excel gestione processi",
    "alternativa Excel gestionale personalizzato PMI Italia",
    "software gestionale cloud vs personalizzato PMI 2026",
    "agenti AI nativi gestionale PMI 2026 integrazione",
    "gestionale su misura vs SaaS cloud PMI costi totali",
    "web agency italiana prezzi reali senza sorprese 2026",
    "voucher doppia transizione 2026 contributo fondo perduto PMI",
    "bandi digitalizzazione 2026 PMI fondo perduto sito web gestionale",
    "contributo 70 percento sito web PMI Unioncamere 2026",
    "consulenza digitale gratuita PMI freelancer Catania Italia",
    "cybersecurity NIS2 PMI 2026 sito web protetto",
    "AI cloud digitalizzazione PMI contributo fondo perduto 2026",
    "88 percento PMI italiane invisibile ChatGPT Gemini Perplexity",
    "visibilità AI motori intelligenza artificiale PMI 2026",
    "PMI invisibile ChatGPT Gemini Perplexity SearchGPT Italia",
    "GEO generative engine optimization agenzia Italia 2026",
    "ottimizzazione visibilità AI PMI freelancer Italia",
    "azienda citata ChatGPT come ottimizzare PMI Italia",
    "strategia visibilità AI PMI 2026 Politecnico Milano",
    "41 percento PMI italiane senza gestionale strutturato ISTAT 2026",
    "solo 21 percento PMI italiane riceve ordini online ISTAT",
    "64 percento piccole imprese spende meno 1000 euro primo sito web",
    "sito web PMI come ricevere ordini online integrazione e-commerce",
    "gestionale cloud PMI accesso remoto smart working Italia",
    "software gestionale ibrido cloud on-premise piccola impresa 2026",
    "ERP cloud alternativa suite enterprise PMI italiana economica",
    "ISTAT digitalizzazione PMI italiane dati 2026",
    "web agency PMI 5 15 dipendenti servizi completi seo sviluppo",
    "sito web vetrina professionale 700 800 euro prezzo reale Italia",
    "gestionale ordini clienti PMI senza canone mensile web-based",
    "come portare clienti online PMI italiana guida pratica 2026",
    "perché solo 21 percento PMI vende online soluzione sito web",
    "sito web fotografo professionista prezzo 2026 Italia",
    "quanto costa sito web per fotografo matrimoni Italia",
    "sito web studio fotografico portfolio online SEO 2026",
    "fotografo aziendale sito web prenotazione sessioni online",
    "SEO fotografo matrimoni città Google 2026",
    "portfolio fotografico online ottimizzato Google Immagini",
    "sito web tatuatore tattoo studio 2026 prezzo",
    "gestionale tatuatore prenotazione appuntamenti online",
    "tattoo studio sito web portfolio SEO locale 2026",
    "tatuatore digitale gestionale clienti lista attesa",
    "sito web wedding planner Italia prezzo 2026",
    "organizzatore matrimoni sito web portfolio SEO",
    "wedding planner trovare clienti online Google 2026",
    "quanto costa sito wedding planner organizzatore eventi Italia",
    "sito web organizzatore eventi preventivo online SEO",
    "Factorial alternativa gestionale PMI economico su misura",
    "Zucchetti alternativa gestionale personalizzato piccola impresa",
    "Synalla CRM alternativa gestionale PMI 2026",
    "zero click search SEO 2026 visibilità PMI Google",
    "ricerche vocali sito web PMI 2026 ottimizzazione",
    "78 percento PMI gestionale miglioramento produttività Osservatorio Digitale",
    "3 secondi decisione utente sito web velocità PMI",
    "local SEO AI Google Business Profile PMI agosto 2026",
  ],
  authors: [{ name: "rec.group" }],
  creator: "rec.group",
  openGraph: {
    title: "Sito Web PMI da €700, Gestionale da €900 — ROI 748% Medio | rec.group 2026",
    description: "Il 72% delle PMI ha un sito — ma solo il 45% è ottimizzato. Noi: siti da €700 e gestionali da €900 (concorrenza: €5.000–8.000). SEO ROI 748%, accessibilità EAA, Core Web Vitals e AI inclusi. Incentivi fino al 70% nel Mezzogiorno. Preventivo gratuito 24h — risponde un umano.",
    type: "website",
    locale: "it_IT",
    siteName: "rec.group",
    url: "https://rec.group",
    images: [
      {
        url: "https://rec.group/og-image.png",
        width: 1200,
        height: 630,
        alt: "rec.group — Sito Web PMI da €700 | Gestionale da €900 | Agenzia Digitale Catania",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Sito Web PMI da €700 — Gestionale €900 Zero Canoni | rec.group 2026",
    description: "88% delle PMI italiane invisibile su ChatGPT, Gemini e Perplexity. Sito da €700, gestionale da €900 zero canoni. ROI SEO 748%. GEO, AEO e EAA inclusi. Incentivi 5.0 + Voucher MISE 50%.",
    images: ["https://rec.group/og-image.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
    },
  },
  alternates: {
    canonical: "https://rec.group",
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": "https://rec.group/#website",
      url: "https://rec.group",
      name: "rec.group — Agenzia Digitale per Freelancer e PMI",
      description:
        "Siti web professionali, gestionali su misura e automazioni digitali per freelancer e PMI italiane. Preventivo gratuito in 24h.",
      inLanguage: "it-IT",
      publisher: { "@id": "https://rec.group/#organization" },
      potentialAction: [
        {
          "@type": "ContactAction",
          target: "https://rec.group/#contatti",
          name: "Richiedi Preventivo Gratuito in 24h",
        },
        {
          "@type": "SearchAction",
          target: {
            "@type": "EntryPoint",
            urlTemplate: "https://rec.group/?q={search_term_string}",
          },
          "query-input": "required name=search_term_string",
        },
      ],
    },
    {
      "@type": "Organization",
      "@id": "https://rec.group/#organization",
      name: "rec.group",
      legalName: "rec.group",
      url: "https://rec.group",
      numberOfEmployees: { "@type": "QuantitativeValue", value: 5 },
      logo: {
        "@type": "ImageObject",
        url: "https://rec.group/logo.png",
        width: 200,
        height: 60,
      },
      email: "recgroup.business@gmail.com",
      description:
        "Agenzia digitale a Catania specializzata in siti web professionali, gestionali personalizzati, social media marketing e automazione per freelancer, PMI, ristoranti e professionisti italiani.",
      foundingLocation: {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          addressLocality: "Catania",
          addressRegion: "Sicilia",
          addressCountry: "IT",
        },
      },
      areaServed: [
        { "@type": "City", name: "Catania" },
        { "@type": "AdministrativeArea", name: "Sicilia" },
        { "@type": "Country", name: "Italia" },
      ],
      slogan: "Soluzioni digitali su misura — zero canoni mensili",
      foundingDate: "2024",
      knowsLanguage: ["it"],
      contactPoint: [
        {
          "@type": "ContactPoint",
          contactType: "customer service",
          email: "recgroup.business@gmail.com",
          availableLanguage: "Italian",
          areaServed: "IT",
        },
        {
          "@type": "ContactPoint",
          contactType: "sales",
          email: "recgroup.business@gmail.com",
          availableLanguage: "Italian",
          areaServed: "IT",
        },
      ],
      sameAs: [],
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.9",
        reviewCount: "13",
        bestRating: "5",
        worstRating: "1",
      },
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "Servizi Digitali rec.group",
        itemListElement: [
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-sito-web",
              name: "Realizzazione Siti Web Professionali per PMI",
              description:
                "Siti web su misura per freelancer, PMI e professionisti. Design moderno, ottimizzazione SEO e velocità garantita. Online in 1–2 settimane.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
            priceSpecification: {
              "@type": "PriceSpecification",
              price: "700",
              priceCurrency: "EUR",
              description: "Sito vetrina professionale con SEO incluso",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-gestionale",
              name: "Software Gestionale Personalizzato per Piccola Impresa",
              description:
                "Gestionali web-based su misura per piccole e medie imprese: prenotazioni, magazzino, clienti, fatturazione. ROI medio in 6–12 mesi.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
            priceSpecification: {
              "@type": "PriceSpecification",
              price: "900",
              priceCurrency: "EUR",
              description: "Gestionale personalizzato una tantum",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-social",
              name: "Social Media Management per PMI",
              description:
                "Gestione social media professionale con strategia di contenuti, post creativi e crescita organica per la tua azienda italiana.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-automazione",
              name: "Automazione Digitale e CRM per Freelancer",
              description:
                "Automazioni per risparmiare 8–15 ore a settimana: CRM, email marketing, flussi di lavoro automatizzati e integrazioni tra app.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-ecommerce",
              name: "E-commerce Professionale per PMI",
              description:
                "Shop online ottimizzato SEO con catalogo prodotti, pagamenti, gestione ordini e Google Shopping. Mercato e-commerce italiano: 71 miliardi nel 2026.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
            priceSpecification: {
              "@type": "PriceSpecification",
              price: "1500",
              priceCurrency: "EUR",
              description: "E-commerce completo con SEO e-commerce incluso",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-menu",
              name: "Menu Digitale QR Code per Ristoranti",
              description:
                "Menu QR code interattivo e aggiornabile in tempo reale per ristoranti, bar e locali in Sicilia e Italia.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: [
                { "@type": "AdministrativeArea", name: "Sicilia" },
                { "@type": "Country", name: "Italia" },
              ],
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              "@id": "https://rec.group/#service-identita",
              name: "Brand Identity Digitale per Professionisti e PMI",
              description:
                "Identità digitale completa: logo, palette colori, tipografia e presenza coordinata su web e social per freelancer e PMI italiane.",
              provider: { "@id": "https://rec.group/#organization" },
              areaServed: { "@type": "Country", name: "Italia" },
            },
          },
        ],
      },
    },
    {
      "@type": ["LocalBusiness", "InternetMarketingService"],
      "@id": "https://rec.group/#localbusiness",
      name: "rec.group — Agenzia Digitale Catania",
      image: "https://rec.group/logo.png",
      url: "https://rec.group",
      email: "recgroup.business@gmail.com",
      telephone: "",
      address: {
        "@type": "PostalAddress",
        addressLocality: "Catania",
        addressRegion: "CT",
        postalCode: "95100",
        addressCountry: "IT",
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: 37.5079,
        longitude: 15.0830,
      },
      description: "Agenzia digitale a Catania: siti web professionali da €700, gestionali su misura da €900 senza canone mensile, automazioni AI e social media per freelancer e PMI in tutta Italia. Preventivo gratuito in 24h.",
      slogan: "Soluzioni digitali su misura — zero canoni mensili",
      priceRange: "€€",
      currenciesAccepted: "EUR",
      paymentAccepted: "Bonifico, Carta di Credito, PayPal",
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.9",
        reviewCount: "13",
        bestRating: "5",
        worstRating: "1",
      },
      openingHoursSpecification: [
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
          opens: "09:00",
          closes: "18:00",
        },
      ],
      knowsAbout: [
        "realizzazione siti web PMI",
        "gestionale personalizzato piccola impresa",
        "social media marketing Catania",
        "automazione digitale freelancer",
        "sito web personal trainer",
        "e-commerce PMI Italia",
        "menu digitale QR code ristorante",
        "identità digitale professionista",
        "agenzia web Sicilia",
        "transizione 5.0 digitalizzazione PMI",
        "intelligenza artificiale piccola impresa",
        "voucher digitalizzazione MISE",
        "automazione workflow n8n make zapier PMI",
        "CRM personalizzato freelancer Italia",
        "fatturazione elettronica integrata gestionale",
        "lead generation automatica piccola impresa",
        "next.js TypeScript sito web veloce PMI",
        "Google Business Profile ottimizzazione locale",
        "preventivi automatici CRM no-code",
        "agenti AI autonomi automazione PMI 2026",
        "software gestionale senza canone mensile",
        "sito web one-page professionale freelancer",
        "web app personalizzata piccola impresa",
        "consulenza digitale PMI Catania Sicilia",
        "green coding sito web sostenibile PMI",
        "GenAI intelligenza artificiale generativa PMI 2026",
        "marketing automation piccola impresa Italia",
        "sito web accessibile WCAG PMI",
        "progressive web app PWA freelancer",
        "chatbot WhatsApp Business automazione PMI",
        "landing page conversione freelancer professionista",
        "schema markup structured data SEO locale",
        "indicizzazione AI Perplexity ChatGPT azienda locale",
        "e-commerce PMI italiane 71 miliardi 2026",
        "brand identity digitale professionista freelancer",
        "ingegnere AI integrazione processi aziendali PMI",
        "voucher consulenza innovazione MIMIT 50 percento",
        "bandi digitalizzazione PMI 2026 finanziamenti",
        "SearchGPT Perplexity ottimizzazione visibilità AI",
        "costo social media manager PMI freelancer Italia",
        "menu digitale allergeni multilingua ristorante",
        "rich snippets Google structured data azienda locale",
        "AI Overviews Google citazione azienda locale 2026",
        "AEO answer engine optimization PMI Italia 2026",
        "marketing locale AI intelligenza artificiale PMI 2026",
        "conversion rate optimization sito web PMI freelancer",
        "bandi regione Sicilia digitalizzazione contributi PMI",
        "voucher doppia transizione 2026 PMI digitalizzazione AI",
        "bandi digitalizzazione a fondo perduto PMI 2026",
        "contributi fondo perduto sito web gestionale PMI Unioncamere",
        "voucher digitalizzazione 70 percento PMI piccola impresa 2026",
        "cybersecurity PMI 2026 NIS2 aggiornamento sito web",
      ],
      makesOffer: [
        { "@id": "https://rec.group/#service-sito-web" },
        { "@id": "https://rec.group/#service-gestionale" },
        { "@id": "https://rec.group/#service-social" },
        { "@id": "https://rec.group/#service-automazione" },
        { "@id": "https://rec.group/#service-ecommerce" },
        { "@id": "https://rec.group/#service-menu" },
        { "@id": "https://rec.group/#service-identita" },
      ],
      hasMap: "https://maps.google.com/?cid=rec.group+catania",
      disambiguatingDescription: "Agenzia web a Catania specializzata in siti web da €700 e gestionali da €900 per freelancer e PMI italiane — zero canoni mensili.",
      serviceArea: [
        { "@type": "City", name: "Catania" },
        { "@type": "AdministrativeArea", name: "Sicilia" },
        { "@type": "Country", name: "Italia" },
      ],
      parentOrganization: { "@id": "https://rec.group/#organization" },
    },
    {
      "@type": "FAQPage",
      "@id": "https://rec.group/#faq",
      mainEntity: [
        {
          "@type": "Question",
          name: "SaaS o gestionale su misura: qual è il costo totale reale su 5 anni per una PMI?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "La domanda giusta non è 'quanto costa svilupparlo?' ma 'quanto spendo in totale nei prossimi 5 anni?'. SaaS mid-range (TeamSystem, Danea, Fatture in Cloud con moduli avanzati): 40–80€/mese per utente = fino a 14.400€ in 5 anni — e al termine non possiedi nulla. Gestionale su misura RecGroup: €900 una tantum + hosting 99€/anno = circa €1.400 in 5 anni. Il software è tuo: nessun vendor lock-in, nessun aumento tariffario, dati esportabili. Risparmio netto su 5 anni: da €5.800 a €16.600 rispetto a un SaaS mid-range. Con incentivi Transizione 5.0 (fino al 45%) il costo effettivo scende a €495–630.",
          },
        },
        {
          "@type": "Question",
          name: "Cosa include esattamente il sito web professionale da €700? Ci sono costi nascosti?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Zero costi nascosti. Incluso da €700: layout personalizzato mobile-first, fino a 6–8 sezioni, velocità sotto i 2 secondi; SEO on-page completo (meta tag, Schema.org, Core Web Vitals verdi, sitemap XML); dominio e hosting primo anno inclusi, certificato SSL, Google Analytics 4 e Search Console configurati; Google Business Profile ottimizzato; formazione 30 min e assistenza WhatsApp 3 mesi. Extra dichiarati nel preventivo: copywriting da zero, fotografia, e-commerce (da €1.500), integrazioni gestionali custom. Nessuna sorpresa in fattura.",
          },
        },
        {
          "@type": "Question",
          name: "Quanto costa un sito web professionale per freelancer o PMI?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Un sito vetrina professionale parte da €700 — design, sviluppo e ottimizzazione SEO inclusi. Per un freelancer che vuole acquisire clienti online è l'investimento con il ROI più rapido: più visibilità, più credibilità, meno tempo perso in preventivi a freddo. Il preventivo è gratuito, dettagliato e senza sorprese.",
          },
        },
        {
          "@type": "Question",
          name: "Conviene un gestionale personalizzato rispetto ai software standard?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "I software generici come TeamSystem o SAP costano 50–150€/mese per utente — e paghi funzioni che non usi mai. Il nostro gestionale su misura parte da €900 una tantum, costruito esatto per il tuo flusso di lavoro. In media le PMI italiane recuperano l'investimento in 6–12 mesi grazie al tempo risparmiato.",
          },
        },
        {
          "@type": "Question",
          name: "Quanto tempo si risparmia davvero con l'automazione dei processi?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Le PMI italiane risparmiano mediamente 8–15 ore a settimana per dipendente dopo aver automatizzato fatturazione, solleciti pagamenti, gestione appuntamenti e report. Per un freelancer o un piccolo studio, significa recuperare 2–4 giorni interi al mese — tempo che puoi rivendere ai clienti.",
          },
        },
        {
          "@type": "Question",
          name: "Le PMI possono accedere agli incentivi fiscali Transizione 5.0?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Sì. Il piano Transizione 5.0 del MIMIT copre fino al 45% degli investimenti in beni digitali per le PMI italiane — siti web, gestionali e automazioni compresi. Un progetto da €2.000 può costarne effettivamente €1.100. Ti aiutiamo a capire cosa spetta alla tua impresa prima ancora di iniziare.",
          },
        },
        {
          "@type": "Question",
          name: "Quanto tempo ci vuole per avere un sito web operativo?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Un sito vetrina è online in 1–2 settimane. Un e-commerce o una piattaforma con area riservata richiede 3–6 settimane. Prima di iniziare ti diamo una data di consegna precisa — e la rispettiamo.",
          },
        },
        {
          "@type": "Question",
          name: "Il sito web include l'ottimizzazione SEO per Google?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Sì, sempre. Ogni sito parte già ottimizzato: struttura semantica, meta tag, Core Web Vitals, mobile-first e velocità di caricamento. Non è un extra a pagamento — è il minimo per comparire su Google e portare traffico organico nel tempo.",
          },
        },
        {
          "@type": "Question",
          name: "Conviene aprire un e-commerce nel 2026? Quali sono i costi reali?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Il mercato e-commerce italiano ha superato i 71 miliardi di euro nel 2026: la domanda c'è. Un e-commerce professionale con RecGroup parte da €1.500 — catalogo prodotti, pagamenti online, gestione ordini e SEO inclusi. Rientri dell'investimento tipici: 6–18 mesi per chi parte da zero.",
          },
        },
        {
          "@type": "Question",
          name: "Le PMI possono integrare l'intelligenza artificiale nella piccola impresa?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Sì, e nel 2026 è più accessibile di quanto pensi. Integriamo chatbot AI sul tuo sito (gestisce l'80% delle domande ricorrenti senza personale), automazioni basate su AI per generare preventivi e documenti in secondi, e dashboard intelligenti che analizzano i tuoi dati di vendita.",
          },
        },
        {
          "@type": "Question",
          name: "Esistono incentivi oltre a Transizione 5.0 per digitalizzare la mia impresa?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Sì. Oltre a Transizione 5.0 (fino al 45%), nel 2026 sono attivi il Voucher Digitalizzazione MISE — contributo a fondo perduto del 50% fino a €10.000 per PMI che investono in siti web, software e formazione digitale — e bandi regionali che variano da regione a regione.",
          },
        },
        {
          "@type": "Question",
          name: "È meglio affidarsi a un'agenzia web o a un freelancer per il mio sito?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Un freelancer lavora da solo: una sola competenza, nessun backup se è indisponibile. Un'agenzia come RecGroup unisce sviluppo, design, SEO e copy su ogni progetto — referente unico, tempi certi. E da noi un sito vetrina parte da €700: spesso meno di quanto chiede un freelancer senior.",
          },
        },
        {
          "@type": "Question",
          name: "Come ottenere più recensioni su Google Maps per far crescere la mia attività locale?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "L'81% dei consumatori italiani legge le recensioni Google prima di contattare un'attività locale — e Google Maps usa le recensioni come segnale di ranking diretto: più recensioni recenti e dettagliate hai, più alta è la probabilità di comparire nel 'local pack'. Cosa funziona nel 2026: chiedi la recensione subito dopo la consegna; invia un link diretto al profilo Google Business Profile via WhatsApp o email; invita il cliente a descrivere il problema risolto, non solo a dare stelle. Con le nostre automazioni WhatsApp Business, la richiesta viene inviata automaticamente 24 ore dopo ogni lavoro completato. Risultato tipico: +15–30 recensioni nei primi 90 giorni, con impatto misurabile sul posizionamento locale.",
          },
        },
        {
          "@type": "Question",
          name: "Google Ads o SEO: cosa conviene di più per una PMI italiana con budget limitato?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Google Ads porta lead in 24 ore ma smette non appena smetti di pagare — costo medio per click in Italia: €0,50–3,00, budget minimo efficace: €300–500/mese per una PMI locale. SEO porta traffico organico gratuito ma richiede 3–6 mesi per i primi risultati con un ROI a lungo termine superiore al 700%. Per una PMI con budget limitato: sito ottimizzato SEO come base permanente (incluso in ogni nostro progetto), Google Ads solo su campagne ad alto margine. Se hai bisogno di contatti entro 30 giorni parti con gli Ads; se vuoi costruire traffico qualificato nel tempo senza pagare per ogni click, investi nel SEO prima.",
          },
        },
        {
          "@type": "Question",
          name: "Lavorate solo a Catania o in tutta Italia?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Siamo di Catania, ma lavoriamo con freelancer e PMI in tutta Italia — da Milano a Palermo. Tutto avviene online: chiamate, consegne, supporto. La distanza non cambia la qualità del risultato.",
          },
        },
        {
          "@type": "Question",
          name: "Quanto costa un sito web per un personal trainer nel 2026? Cosa serve davvero?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Un personal trainer senza sito perde il 60–70% dei potenziali clienti: nel 2026 la ricerca online precede quasi sempre il primo contatto. Il costo medio di un sito per personal trainer da un'agenzia web italiana varia tra €1.500 e €4.000. Con RecGroup un sito completo per personal trainer parte da €700 — prenotazioni sessioni integrate, SEO locale per comparire su Google Maps nella tua città e ottimizzazione per ricerche tipo 'personal trainer vicino a me'. Chi lo abbina al gestionale da €900 automatizza anche pagamenti, schede clienti e programmazione mensile: zero fogli Excel. Consegna in 10–14 giorni.",
          },
        },
        {
          "@type": "Question",
          name: "Cosa sono gli agenti AI e convengono davvero per una piccola impresa italiana?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Un agente AI ragiona, pianifica e agisce in autonomia — qualifica lead, invia email, compila report, prenota appuntamenti senza supervisione umana costante. Nel 2026 il 40% delle applicazioni aziendali integrerà almeno un AI Agent (Gartner 2026). Benefici misurabili nelle PMI: tempi di risposta ridotti del 70%, costi operativi ridotti del 25–40% entro 12 mesi, recupero di 15–25 ore settimanali. Con RecGroup integriamo agenti AI nei gestionali su misura da €1.500 — con Transizione 5.0 (45%) il costo effettivo scende a circa €825.",
          },
        },
        {
          "@type": "Question",
          name: "Differenza tra sito vetrina, sito aziendale e web app per una PMI: quale scegliere nel 2026?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Tre strumenti diversi per tre obiettivi diversi. Sito vetrina (da €700): 4–8 pagine per credibilità e acquisizione contatti — la scelta giusta per freelancer, artigiani e PMI che vogliono comparire su Google e ricevere preventivi online. Sito aziendale strutturato (da €1.200): blog, portfolio esteso, più sezioni di servizio — consigliato per PMI con più linee di prodotto che vogliono autorità SEO nel tempo. Web app / gestionale (da €900): applicazione interattiva con login, dashboard e funzionalità operative — prenotazioni, CRM, fatturazione, magazzino. Regola pratica: se vuoi trovare clienti → sito vetrina SEO; se vuoi gestire clienti ed eliminare Excel → gestionale su misura; se vuoi entrambi, si integrano nello stesso preventivo.",
          },
        },
        {
          "@type": "Question",
          name: "Il 93% delle aziende italiane è online, ma solo il 15% intercetta clienti su Google: perché?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Il gap tra presenza online e acquisizione clienti si spiega con 5 errori strutturali: (1) sito senza SEO tecnico — meta tag generici, struttura semantica errata, assenza di Schema.org; (2) Core Web Vitals insufficienti — Google penalizza nel ranking i siti con caricamento superiore a 2,5 secondi, e oltre il 60% dei siti PMI italiani fallisce questo test; (3) design non mobile-first — oltre il 70% delle ricerche avviene da smartphone; (4) contenuti assenti o generici — senza keyword specifiche il sito è invisibile per le ricerche del tuo target; (5) Google Business Profile incompleto — il Local Pack di Google Maps è il canale con il ROI più alto per le attività locali, ma solo il 35% delle PMI ha il profilo ottimizzato. Con RecGroup ogni sito viene consegnato già nella fascia del 15% virtuoso — Core Web Vitals verdi, SEO tecnico, Schema.org e Google Business Profile ottimizzato come standard.",
          },
        },
        {
          "@type": "Question",
          name: "Ho chiesto un preventivo ad altre agenzie e mi chiedono €20.000–60.000 per un gestionale: come fate a svilupparlo da €900?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Le grandi software house quotano €20.000–60.000 per strutture di costo elevate e scope enterprise sproporzionato. RecGroup si differenzia su tre fronti: (1) scope mirato — gestionali per PMI con 1–15 utenti, non corporate da 200 dipendenti; le funzioni per un artigiano o uno studio professionale sono chiare e replicabili; (2) stack moderno e snello — Next.js, database leggeri, hosting cloud senza licenze ERP o middleware inutili; (3) team piccolo, costi fissi minimi — il risparmio va direttamente nel prezzo. Il gestionale da €900 una tantum è tuo per sempre: nessun canone mensile, nessun vendor lock-in. Non è indicato per ERP enterprise da 50+ dipendenti — ma per sostituire Excel, WhatsApp e carta in una PMI piccola è la soluzione con il ROI più rapido sul mercato.",
          },
        },
        {
          "@type": "Question",
          name: "Sito web per dentista, studio dentistico o clinica odontoiatrica nel 2026: cosa serve davvero?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Nel 2026 il 91% dei pazienti cerca un dentista su Google prima di prenotare. Un sito efficace per studio odontoiatrico include: pagina servizi ottimizzata per keyword locali ('dentista [città]', 'ortodontista [quartiere]'); sistema di prenotazione appuntamenti online con conferma automatica via WhatsApp; scheda Google Business Profile ottimizzata con foto e recensioni; sezione FAQ medica per le domande più cercate ('quanto costa un impianto dentale?'); conformità GDPR per dati sanitari sensibili. Con RecGroup un sito per studio dentistico parte da €700 — prenotazioni integrate, SEO locale e conformità normativa. Il gestionale da €900 abbinato elimina l'agenda cartacea. Consegna in 2 settimane.",
          },
        },
        {
          "@type": "Question",
          name: "Sito web per B&B, affittacamere o casa vacanze nel 2026: come ridurre le commissioni Booking.com?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Booking.com e Airbnb prendono il 15–30% su ogni prenotazione — per una struttura con €20.000 di fatturato annuo significa perdere €3.000–6.000/anno in commissioni. Un sito con prenotazione diretta recupera queste commissioni già dalla prima stagione. Include: motore di prenotazione con disponibilità in tempo reale e pagamento online; integrazione channel manager per evitare doppie prenotazioni; SEO locale per 'B&B [città]' e 'affittacamere [zona]'; schema markup LodgingBusiness per i rich snippet su Google. Con RecGroup un sito per B&B con booking diretto parte da €1.200 — con 3–4 prenotazioni dirette al mese risparmiate dalla commissione, il ROI è completo in pochi mesi.",
          },
        },
        {
          "@type": "Question",
          name: "L'88% delle PMI italiane è invisibile su ChatGPT, Gemini e Perplexity: come risolvere?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Secondo il Politecnico di Milano (2026), solo il 12% delle PMI italiane ha una strategia per la visibilità sui motori AI — l'88% è completamente assente su ChatGPT, Gemini, Perplexity e SearchGPT. Questo significa perdere clienti che non cercano più su Google ma chiedono direttamente a un AI. Come risolvere: (1) contenuti strutturati con Schema.org che i motori AI leggono e citano; (2) FAQ con risposte dirette a domande reali — la forma preferita dai modelli AI per generare risposte; (3) menzione del brand su fonti autorevoli che gli AI indicizzano; (4) ottimizzazione GEO (Generative Engine Optimization) del sito — diversa dalla SEO classica. Con RecGroup ogni progetto include ottimizzazione GEO e AEO di base: il tuo brand diventa citabile dagli AI al posto dei concorrenti.",
          },
        },
        {
          "@type": "Question",
          name: "Conviene un sito web per estetista, parrucchiere o centro estetico nel 2026?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Nel 2026 Treatwell e Fresha trattengono il 20–30% su ogni prenotazione. Per un centro estetico con 600€/giorno di fatturato, significa 1.800–3.600€/mese di commissioni. Un sito con prenotazione diretta recupera quelle commissioni già dal primo mese. Con RecGroup un sito per estetista o parrucchiere parte da €700 — prenotazioni online con promemoria WhatsApp automatici, gallery trattamenti, SEO locale ('estetista [città]', 'parrucchiere [quartiere]') e pagina recensioni integrata. Consegna in 10–14 giorni. Il gestionale da €900 elimina l'agenda cartacea e automatizza i solleciti per clienti non tornati da 60+ giorni.",
          },
        },
        {
          "@type": "Question",
          name: "Il gestionale su misura RecGroup conviene rispetto a Gestify, Planet Premium o iMio per idraulici ed elettricisti?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "I software verticali per impiantisti come Gestify, Planet Premium o iMio costano 40–120€/mese per utente — per 3 tecnici: 1.440–4.320€/anno in perpetuo senza mai possedere il software. Il gestionale RecGroup parte da €900 una tantum con preventivi e rapportini digitali da smartphone, agenda tecnici, magazzino con alert riordino, fatturazione SDI e storico impianti. Su 5 anni per 3 utenti: SaaS verticale = €7.200–21.600; RecGroup = circa €1.400 totali. Con Transizione 5.0 (45%) il costo effettivo scende a circa €495. Indicato per imprese con 1–10 operatori — il TCO più basso del mercato per artigiani idraulici ed elettricisti italiani.",
          },
        },
        {
          "@type": "Question",
          name: "WordPress o sito custom: quale scegliere per una PMI nel 2026?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "WordPress ha un costo d'ingresso basso ma nasconde costi ricorrenti che molti non calcolano: hosting dedicato 50–120€/mese, theme premium 200–400€/anno, plugin premium 100–300€/anno, aggiornamenti e manutenzione di sicurezza 30–60€/mese. In 5 anni una PMI tipica spende 5.000–9.000€ su un sito WordPress 'economico'. Un sito custom con RecGroup (Next.js, TypeScript) parte da €700 una tantum: hosting cloud 99€/anno, zero plugin, zero aggiornamenti obbligatori, zero vendor lock-in. Performance superiori: caricamento medio 0,8 secondi contro 2,5–4 secondi di WordPress non ottimizzato — e Core Web Vitals sono un fattore di ranking diretto su Google. Scelta pratica: se pubblichi articoli ogni settimana e hai un team editoriale → WordPress con cura. Se vuoi acquisire clienti online con costi certi e performance garantite → sito custom da €700.",
          },
        },
        {
          "@type": "Question",
          name: "Quanto tempo ci vuole per vedere risultati SEO con un sito web nuovo per una PMI?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "La risposta onesta che poche agenzie ti danno: dipende dalla concorrenza locale e dalle keyword target. In linea di massima per una PMI locale (es. 'idraulico Catania', 'estetista Roma Prati'): 4–8 settimane per la prima indicizzazione di tutte le pagine; 2–4 mesi per posizionarsi in prima pagina su keyword locali a bassa concorrenza; 4–8 mesi per keyword competitive con volumi significativi. Cosa accelera il processo: Core Web Vitals verdi (inclusi in ogni nostro sito), Schema.org completo con LocalBusiness, contenuti FAQ ottimizzati per le domande reali degli utenti, Google Business Profile ottimizzato con foto e recensioni recenti, link da directory locali autorevoli (Pagine Gialle, TripAdvisor, Yelp). Con RecGroup ogni sito viene consegnato già indicizzabile al massimo — senza il mese di setup tecnico che molte agenzie fanno pagare a parte.",
          },
        },
        {
          "@type": "Question",
          name: "Sito web per fotografo professionista o studio fotografico nel 2026: cosa serve davvero?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Un fotografo professionista senza sito web ottimizzato SEO dipende solo dal passaparola e da Instagram — che porta follower, non sempre clienti con intento immediato. Con RecGroup un sito per fotografo parte da €700: portfolio galleria ottimizzata per Google Immagini con schema markup Photographer, pagina servizi (matrimoni, corporate, ritratti, prodotto, eventi), sistema di prenotazione sessioni online, SEO locale per keyword come 'fotografo matrimonio [città]' e 'shooting aziendale [zona]'. Il gestionale da €900 abbinato centralizza clienti, sessioni, consegne e fatturazione. Consegna in 10–14 giorni.",
          },
        },
        {
          "@type": "Question",
          name: "Sito web e gestionale per tatuatore o tattoo studio nel 2026: come digitalizzarsi davvero?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Il 74% delle richieste ai tatuatori italiani arriva da Google Maps e ricerche locali. Un tattoo studio senza sito web perde prenotazioni ogni giorno. Con RecGroup: sito con portfolio per stile (realistico, minimal, blackwork) da €700, sistema di prenotazione online con lista d'attesa digitale e promemoria WhatsApp (-40–60% no-show), SEO locale per 'tatuatore [città]', pagamento acconto online. Il gestionale da €900 gestisce clienti, appuntamenti e fatturazione. Con Transizione 5.0 (45%) il pacchetto completo scende a circa €880. Consegna in 2 settimane.",
          },
        },
        {
          "@type": "Question",
          name: "Sito web per wedding planner o organizzatore di eventi nel 2026: come trovare più coppie online?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Il 91% delle coppie italiane inizia la ricerca del wedding planner su Google — e le prime 3 posizioni su 'wedding planner [città]' raccolgono l'85% dei click. Con RecGroup un sito per wedding planner parte da €700: portfolio matrimoni con SEO per ogni storia, pagina pacchetti con prezzi trasparenti, modulo preventivo che qualifica i lead, testimonianze sposi, SEO locale per 'wedding planner [città]' e 'organizzatore matrimoni [regione]', schema markup EventPlanner. Il gestionale da €900 abbinato gestisce clienti, fornitori, checklist eventi e fatturazione. Consegna in 1–2 settimane.",
          },
        },
        {
          "@type": "Question",
          name: "Come si inizia a lavorare con RecGroup?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Con una chiamata gratuita di 30 minuti. Raccontaci il tuo progetto, le difficoltà attuali e gli obiettivi. Riceverai una proposta su misura entro 48 ore — senza impegno e senza costi anticipati.",
          },
        },
      ],
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-sito-web",
      name: "Realizzazione Siti Web Professionali per PMI e Freelancer",
      description:
        "Siti web su misura per freelancer, PMI e professionisti italiani. Design moderno mobile-first, ottimizzazione SEO, Core Web Vitals e velocità garantita. Online in 1–2 settimane da €700 tutto incluso.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Sviluppo Web",
      serviceOutput: {
        "@type": "WebSite",
        name: "Sito web professionale mobile-first con SEO ottimizzato",
        description: "Sito vetrina online in 1–2 settimane: design su misura, Core Web Vitals verdi, SEO on-page, Google Analytics 4 e Google Business Profile configurati.",
      },
      offers: {
        "@type": "Offer",
        price: "700",
        priceCurrency: "EUR",
        priceValidUntil: "2026-12-31",
        availability: "https://schema.org/InStock",
        eligibleRegion: { "@type": "Country", name: "Italia" },
        description: "Sito vetrina professionale con SEO incluso",
      },
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-gestionale",
      name: "Software Gestionale Personalizzato per Piccola Impresa",
      description:
        "Gestionali web-based costruiti sul tuo flusso di lavoro: prenotazioni online, magazzino, clienti, fatturazione e report. Nessun canone mensile — pagamento una tantum da €900. ROI medio in 6–12 mesi.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Sviluppo Software",
      serviceOutput: {
        "@type": "SoftwareApplication",
        applicationCategory: "BusinessApplication",
        name: "Gestionale web personalizzato",
        description: "Applicazione web su misura con prenotazioni, CRM, magazzino e fatturazione — accessibile da qualsiasi dispositivo, nessuna installazione.",
        operatingSystem: "Web, iOS, Android",
      },
      offers: {
        "@type": "Offer",
        price: "900",
        priceCurrency: "EUR",
        priceValidUntil: "2026-12-31",
        availability: "https://schema.org/InStock",
        eligibleRegion: { "@type": "Country", name: "Italia" },
        description: "Gestionale personalizzato una tantum senza canone mensile",
      },
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-automazione",
      name: "Automazione Digitale e CRM per Freelancer e PMI Italiane",
      description:
        "Automazioni AI che risparmiano 8–15 ore a settimana: CRM, email marketing automatizzato, flussi di lavoro, integrazioni tra app e chatbot AI. Per freelancer e PMI italiane che vogliono crescere senza assumere.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Automazione Digitale",
      serviceOutput: {
        "@type": "SoftwareApplication",
        applicationCategory: "BusinessApplication",
        name: "Flussi di automazione e CRM integrato",
        description: "Workflow automatizzati con n8n, Make o Zapier: CRM, email marketing, chatbot WhatsApp Business e integrazioni tra app aziendali.",
      },
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-social",
      name: "Social Media Marketing Professionale per PMI e Freelancer",
      description:
        "Gestione social media completa per freelancer e PMI italiane: strategia mensile, piano editoriale, contenuti professionali, campagne sponsorizzate e report con KPI reali. Post che generano richieste di preventivo — non solo like. Crescita organica e advertising su Instagram, Facebook, LinkedIn e TikTok.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Social Media Marketing",
      category: "Marketing Digitale",
      audience: {
        "@type": "Audience",
        audienceType: "Freelancer, PMI e professionisti italiani",
      },
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-ecommerce",
      name: "Realizzazione E-commerce Professionale per PMI Italiane",
      description:
        "Shop online ottimizzato SEO per PMI italiane: catalogo prodotti, pagamenti sicuri, gestione ordini, spedizioni e integrazione Google Shopping. Mercato e-commerce italiano oltre 71 miliardi nel 2026. ROI tipico: rientro dell'investimento in 6–18 mesi. Da €1.500 tutto incluso.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Sviluppo E-commerce",
      category: "Commercio Elettronico",
      serviceOutput: {
        "@type": "WebSite",
        name: "Shop online professionale ottimizzato SEO",
        description: "E-commerce con catalogo prodotti, pagamenti sicuri, gestione ordini, spedizioni e integrazione Google Shopping — mobile-first e Core Web Vitals ottimizzati.",
      },
      offers: {
        "@type": "Offer",
        price: "1500",
        priceCurrency: "EUR",
        priceValidUntil: "2026-12-31",
        availability: "https://schema.org/InStock",
        eligibleRegion: { "@type": "Country", name: "Italia" },
        description: "E-commerce completo con SEO, pagamenti e gestione ordini inclusi",
      },
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-menu",
      name: "Menu Digitale QR Code per Ristoranti Bar e Locali",
      description:
        "Menu digitale interattivo con QR code per ristoranti, bar, pizzerie e locali in Italia: aggiornabile in tempo reale, zero costi di stampa, design coordinato al brand. I clienti scansionano dal tavolo — tu aggiorni prezzi e piatti in un click. Multilingua, allergeni e foto piatti inclusi.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: [
        { "@type": "AdministrativeArea", name: "Sicilia" },
        { "@type": "Country", name: "Italia" },
      ],
      serviceType: "Menu Digitale QR Code",
      category: "Ristorazione Digitale",
    },
    {
      "@type": "Service",
      "@id": "https://rec.group/#service-identita",
      name: "Brand Identity Digitale per Professionisti e PMI",
      description:
        "Identità digitale completa per freelancer, professionisti e PMI italiane: logo professionale, palette colori, tipografia, tono di voce e presenza coordinata su web e social media. Un brand riconoscibile che ti differenzia dalla concorrenza locale e aumenta la fiducia dei clienti.",
      provider: { "@id": "https://rec.group/#organization" },
      areaServed: { "@type": "Country", name: "Italia" },
      serviceType: "Brand Identity",
      category: "Identità Visiva e Branding",
    },
    {
      "@type": "ItemList",
      "@id": "https://rec.group/#service-list",
      name: "Tutti i Servizi Digitali rec.group per Freelancer e PMI",
      description: "Lista completa dei servizi digitali offerti da rec.group: siti web, gestionali, e-commerce, automazioni, social media, menu digitali e brand identity per freelancer e PMI italiane.",
      numberOfItems: 7,
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Siti Web Professionali da €700",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-sito-web" },
        },
        {
          "@type": "ListItem",
          position: 2,
          name: "Gestionali Personalizzati da €900",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-gestionale" },
        },
        {
          "@type": "ListItem",
          position: 3,
          name: "E-commerce Professionale da €1.500",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-ecommerce" },
        },
        {
          "@type": "ListItem",
          position: 4,
          name: "Automazione Digitale e CRM",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-automazione" },
        },
        {
          "@type": "ListItem",
          position: 5,
          name: "Social Media Marketing PMI",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-social" },
        },
        {
          "@type": "ListItem",
          position: 6,
          name: "Menu Digitale QR Code Ristoranti",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-menu" },
        },
        {
          "@type": "ListItem",
          position: 7,
          name: "Brand Identity Digitale",
          url: "https://rec.group/#servizi",
          item: { "@id": "https://rec.group/#service-identita" },
        },
      ],
    },
    {
      "@type": "SoftwareApplication",
      "@id": "https://rec.group/#software-gestionale",
      name: "Gestionale PMI su Misura — rec.group",
      applicationCategory: "BusinessApplication",
      applicationSubCategory: "Gestionale Web PMI",
      operatingSystem: "Web, iOS, Android",
      description:
        "Software gestionale web-based personalizzato per piccola impresa: prenotazioni online, CRM clienti, magazzino, fatturazione e report automatici. Pagamento una tantum da €900 — zero canoni mensili. ROI medio in 6–12 mesi per PMI italiane.",
      featureList: [
        "Gestione prenotazioni online",
        "CRM clienti personalizzato",
        "Fatturazione e preventivi automatici",
        "Report e dashboard dati",
        "Integrazione pagamenti online",
        "Accesso multi-dispositivo",
        "Backup automatico dati",
        "Supporto incluso nel prezzo",
      ],
      softwareVersion: "1.0",
      inLanguage: "it-IT",
      provider: { "@id": "https://rec.group/#organization" },
      audience: {
        "@type": "Audience",
        audienceType: "Freelancer e PMI italiane con 1–20 dipendenti",
        geographicArea: { "@type": "Country", name: "Italia" },
      },
      offers: {
        "@type": "Offer",
        price: "900",
        priceCurrency: "EUR",
        priceValidUntil: "2026-12-31",
        availability: "https://schema.org/InStock",
        description: "Gestionale personalizzato una tantum — nessun canone mensile",
        seller: { "@id": "https://rec.group/#organization" },
      },
    },
    {
      "@type": "WebPage",
      "@id": "https://rec.group/#webpage",
      url: "https://rec.group",
      name: "Sito Web da €700 per PMI e Freelancer | rec.group Catania",
      isPartOf: { "@id": "https://rec.group/#website" },
      about: { "@id": "https://rec.group/#organization" },
      primaryImageOfPage: {
        "@type": "ImageObject",
        url: "https://rec.group/og-image.png",
        width: 1200,
        height: 630,
      },
      datePublished: "2024-01-01",
      dateModified: "2026-08-03",
      description:
        "Siti web professionali da €700, gestionali su misura da €900 senza canone mensile e automazioni AI per freelancer e PMI italiane. Preventivo gratuito in 24h.",
      breadcrumb: { "@id": "https://rec.group/#breadcrumb" },
      inLanguage: "it-IT",
      speakable: {
        "@type": "SpeakableSpecification",
        cssSelector: ["h1", "h2", "[data-speakable]"],
      },
      potentialAction: {
        "@type": "ReadAction",
        target: ["https://rec.group"],
      },
    },
    {
      "@type": "HowTo",
      "@id": "https://rec.group/#howto-progetto",
      name: "Come avviare il tuo progetto digitale con RecGroup",
      description:
        "Guida passo-passo per freelancer e PMI italiane: dalla chiamata gratuita alla consegna del sito web o gestionale su misura. Tutto online, senza impegno.",
      totalTime: "P14D",
      estimatedCost: {
        "@type": "MonetaryAmount",
        currency: "EUR",
        value: "700",
      },
      step: [
        {
          "@type": "HowToStep",
          position: 1,
          name: "Richiedi un preventivo gratuito",
          text: "Compila il modulo di contatto o scrivi a recgroup.business@gmail.com. Rispondiamo entro 24 ore con una proposta su misura — senza impegno e senza costi anticipati.",
          url: "https://rec.group/#contatti",
        },
        {
          "@type": "HowToStep",
          position: 2,
          name: "Chiamata conoscitiva di 30 minuti",
          text: "Raccontaci il tuo progetto, le difficoltà attuali e gli obiettivi di business. Analizziamo insieme le esigenze specifiche della tua attività e identifichiamo la soluzione digitale più efficace.",
        },
        {
          "@type": "HowToStep",
          position: 3,
          name: "Ricevi la proposta dettagliata entro 48 ore",
          text: "Ti inviamo una proposta completa con tempi, costi e funzionalità — tutto trasparente, senza costi nascosti. Sito web da €700, gestionale da €900, automazioni su misura.",
        },
        {
          "@type": "HowToStep",
          position: 4,
          name: "Sviluppo e consegna del progetto",
          text: "Sito vetrina online in 1–2 settimane, e-commerce in 3–6 settimane. Ti diamo una data di consegna precisa e la rispettiamo. Supporto incluso nel prezzo dopo la consegna.",
        },
      ],
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-1",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Luca M." },
      reviewBody: "Sito professionale consegnato in 12 giorni, SEO già visibile su Google dopo 3 settimane. Prezzo onesto, zero sorprese in fattura.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-04-15",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-2",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Alessia T." },
      reviewBody: "Ho sostituito TeamSystem con il loro gestionale su misura da €900. Ho recuperato l'investimento in 7 mesi solo di abbonamenti risparmiati. Consigliatissimi.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-05-20",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-3",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Davide R." },
      reviewBody: "Automazioni WhatsApp Business e CRM integrato: risparmio 10 ore a settimana. Il chatbot AI gestisce il 70% delle domande dei clienti senza di me.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-06-08",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-4",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Marta S." },
      reviewBody: "Sito vetrina online in 11 giorni, già prima pagina Google per il mio settore. Il gestionale ha eliminato 3 fogli Excel. Investimento ammortizzato in 4 mesi.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-07-01",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-5",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Simone V." },
      reviewBody: "Preventivo dettagliato in meno di 12 ore — zero voci opache. Quello che mi hanno detto nel preventivo è esattamente quello che ho pagato. Sito online in 10 giorni, gestionale consegnato in 3 settimane. La chiarezza sui prezzi è rara in questo mercato.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-07-07",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-6",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Francesca B." },
      reviewBody: "Avevo tre fogli Excel per gestire clienti, appuntamenti e pagamenti. Il gestionale su misura da €900 ha eliminato tutto. ROI chiaro: risparmio 12 ore a settimana, investimento recuperato in 5 mesi. Migliore decisione digitale dell'anno.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-07-13",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-7",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Giorgio P." },
      reviewBody: "Cercavo alternativa al mio sito WordPress: €60/mese di hosting, template a €200/anno e aggiornamenti continui che bloccavano tutto. Con RecGroup ho un sito Next.js da €700 — caricamento in 0,8 secondi, Core Web Vitals verdi, zero canoni mensili. In 4 mesi le visite organiche sono triplicate.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-07-28",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-8",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Chiara N." },
      reviewBody: "Fisioterapista freelance: avevo solo un profilo Instagram. Ora ho un sito con prenotazioni online e sono prima su Google per 'fisioterapista Catania'. Il gestionale da €900 ha eliminato l'agenda cartacea. In 2 mesi ho già 4 nuovi pazienti organici al mese grazie al sito.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-07-31",
      inLanguage: "it-IT",
    },
    {
      "@type": "Review",
      "@id": "https://rec.group/#review-9",
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      author: { "@type": "Person", name: "Marco L." },
      reviewBody: "Cercavo alternativa a Factorial e Zucchetti per il mio studio. Il gestionale su misura da €900 fa tutto quello che mi serviva — preventivi, clienti, agenda — senza pagare funzioni inutili. Recuperato in 4 mesi di canoni risparmiati.",
      itemReviewed: { "@id": "https://rec.group/#organization" },
      datePublished: "2026-08-03",
      inLanguage: "it-IT",
    },
    {
      "@type": "ServiceChannel",
      "@id": "https://rec.group/#channel-email",
      name: "Preventivo Gratuito via Email — RecGroup",
      serviceUrl: "https://rec.group/#contatti",
      contactPoint: {
        "@type": "ContactPoint",
        contactType: "sales",
        email: "recgroup.business@gmail.com",
        availableLanguage: "Italian",
        areaServed: "IT",
        contactOption: "TollFree",
        hoursAvailable: {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
          opens: "09:00",
          closes: "18:00",
        },
      },
      providesService: [
        { "@id": "https://rec.group/#service-sito-web" },
        { "@id": "https://rec.group/#service-gestionale" },
        { "@id": "https://rec.group/#service-automazione" },
        { "@id": "https://rec.group/#service-ecommerce" },
        { "@id": "https://rec.group/#service-social" },
        { "@id": "https://rec.group/#service-menu" },
        { "@id": "https://rec.group/#service-identita" },
      ],
      processingTime: "P1D",
      description: "Richiedi un preventivo gratuito per sito web, gestionale o automazioni — risposta umana entro 24 ore, senza impegno e senza costi anticipati.",
    },
    {
      "@type": "BreadcrumbList",
      "@id": "https://rec.group/#breadcrumb",
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: "https://rec.group",
        },
        {
          "@type": "ListItem",
          position: 2,
          name: "Servizi Digitali",
          item: "https://rec.group/#servizi",
        },
        {
          "@type": "ListItem",
          position: 3,
          name: "Portfolio Progetti",
          item: "https://rec.group/#portfolio",
        },
        {
          "@type": "ListItem",
          position: 4,
          name: "Preventivo Gratuito",
          item: "https://rec.group/#contatti",
        },
      ],
    },
    {
      "@type": "SpecialAnnouncement",
      "@id": "https://rec.group/#announcement-voucher-doppia-transizione-2026",
      name: "Voucher Doppia Transizione 2026: fino al 70% a fondo perduto per PMI",
      text: "Unioncamere ha stanziato €150 milioni (2026–2029) per il Voucher Doppia Transizione: contributi fino al 70% a fondo perduto per PMI italiane che investono in AI, cloud, cybersecurity, IoT e digitalizzazione. Oltre a Transizione 5.0 (45% tax credit) e Voucher MISE (50% fino a €10.000), nel 2026 sono attivi più strumenti combinabili. RecGroup analizza gratuitamente quali incentivi spettano alla tua impresa prima di firmare il preventivo — nessun costo anticipato.",
      datePosted: "2026-07-16",
      expires: "2026-12-31",
      spatialCoverage: { "@type": "Country", name: "Italia" },
      announcementLocation: {
        "@type": "VirtualLocation",
        url: "https://rec.group/#contatti",
      },
      url: "https://rec.group/#contatti",
      author: { "@id": "https://rec.group/#organization" },
      inLanguage: "it-IT",
    },
    {
      "@type": "Event",
      "@id": "https://rec.group/#event-consulenza-gratuita",
      name: "Consulenza Digitale Gratuita 30 Minuti per PMI e Freelancer",
      description:
        "Chiamata gratuita di 30 minuti con il team RecGroup: analizziamo il tuo progetto digitale (sito web, gestionale, automazioni AI), identifichiamo la soluzione più efficace per la tua attività e ti diciamo quali incentivi 2026 (Transizione 5.0, Voucher Doppia Transizione, bandi regionali) puoi usare — senza impegno e senza costi anticipati.",
      eventStatus: "https://schema.org/EventScheduled",
      eventAttendanceMode: "https://schema.org/OnlineEventAttendanceMode",
      location: {
        "@type": "VirtualLocation",
        url: "https://rec.group/#contatti",
      },
      organizer: { "@id": "https://rec.group/#organization" },
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "EUR",
        availability: "https://schema.org/InStock",
        description: "Consulenza gratuita senza impegno — risponde un esperto RecGroup in 24h",
        seller: { "@id": "https://rec.group/#organization" },
      },
      startDate: "2026-07-16",
      endDate: "2026-12-31",
      inLanguage: "it-IT",
      isAccessibleForFree: true,
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it" className="h-full antialiased">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
